# Generated by Django 3.1.8 on 2022-05-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYC', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
